# Generated by Django 2.2.3 on 2019-07-05 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_auto_20190705_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='portfolio_site',
            field=models.URLField(blank=True),
        ),
    ]
